# Host to use for canonical URL generation (without trailing slash)
host: https://www.docs.verify.service.gov.uk

# Header-related options
show_govuk_logo: true
service_name: Verify
service_link: https://www.verify.service.gov.uk/
phase:

# Links to show on right-hand-side of header
header_links:
  Connecting: https://www.verify.service.gov.uk/connecting/
  Documentation: /
  Support: https://www.verify.service.gov.uk/support/

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id: UA-26179049-26

# Table of contents depth â€“ how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 1

# Show a block at the bottom of the page that links to the page source, so readers can easily contribute back to the documentation.

show_contribution_banner: true
github_repo: alphagov/verify-tech-docs/

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: false

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Enable search functionality
enable_search: true

# Enable API reference genration from OpenAPI v3 spec
# For example: https://raw.githubusercontent.com/alphagov/verify-service-provider/53d28ebec44b7ca99f0b9675bab5fb60e0145e60/docs/api/verify-service-provider-api.swagger-v2.yml

api_path:

# Set default slack workspace and owner
owner_slack_workspace: gds
default_owner_slack: '#bot-testing'
